services:
  master:
    build:
      context: .
      dockerfile: master_service/Dockerfile
    container_name: leader
    ports:
      - "8000:8000"
    networks:
      - replicated-net
    volumes:
      - ./master_service:/app:ro
    environment:
      - PYTHONUNBUFFERED=1

  follower_1:
    build:
      context: .
      dockerfile: secondary_service/Dockerfile
    container_name: follower-1
    ports:
      - "8001:8000"
    networks:
      - replicated-net
    depends_on:
      - master
    volumes:
      - ./secondary_service:/app:ro
    environment:
      - SERVICE_NAME=Follower-1
#      - DELAY=5
      - PYTHONUNBUFFERED=1

  follower_2:
    build:
      context: .
      dockerfile: secondary_service/Dockerfile
    container_name: follower-2
    ports:
      - "8002:8000"
    networks:
      - replicated-net
    depends_on:
      - master
    volumes:
      - ./secondary_service:/app:ro
    environment:
      - SERVICE_NAME=Follower-2
      - PYTHONUNBUFFERED=1
      -  DELAY=60
networks:
  replicated-net:
    driver: bridge